# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
version: "{build}"

init:
  - appveyor version
  - git config --global core.autocrlf input

platform:
  - x86

install:
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
  - cmd: SET PATH=C:\python27;%PATH%
  - cmd: python script/cibuild

branches:
  only:
    - master

# disable build and test pahses
build: off
test: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
